### ISSUE TITLE
Exception on opening file without extension

### ISSUE THREAD

**Issue by AlexSnowLeo** [Rewalon/SubReal.EasyDuplicatesFinder#3]
**Step to reproduce:**
- Set folder that containing file without extension to search
- Press Search
- Select file without extension
- Select "Open File" in Popup Menu

**Expected result:** nothing or message box with normal message.

**Actual result:**
Exception with trace message:
[exception on opening file without extension.txt](https://github.com/Subreal-Team/SubReal.EasyDuplicatesFinder/files/5627561/exception.on.opening.file.without.extension.txt)

**Comment by Rewalon** [comment]
The error is not reproduced.
Work correctly.
We need more information.
